# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.4
FROM python:3.11-slim
WORKDIR /app
# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*
# Copy project
COPY pyproject.toml requirements.txt ./
# Install Python deps
RUN pip install --no-cache-dir --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.txt
# Copy rest of source
COPY . .
# Ensure script is executable
RUN chmod +x google_ads_server.py
ENTRYPOINT ["python","google_ads_server.py"]
